deployment:
  replicas: 2
  robopd2Ui:
    image:
      repository: clrosier/robopd2-ui
      tag: 1.0.0
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "2"
        memory: 1536Mi
      requests:
        cpu: "1"
        memory: 1Gi
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
